### ISSUE TITLE
Extraction of top 36 bounding boxes

### ISSUE THREAD

**Issue by ak-kat** [nithinraok/VisualQuestion_VQA#1]
In [41] :
predictions = model([image_tensor])

Could you please tell what predictions are ?

Thanks in advance.

**Comment by nithinraok** [comment]
I am not sure which file you are pointing to but running inference on model gives probability of output on one of the answer in 3129 classes. I tested with different class lengths so It may be 3129 or 1000.

**Comment by ak-kat** [comment]
common resources / rpn_test_2.ipynb

Actually I required to extract top 36 regions predicted from faster RCNN, and finally Resnet features for those boxes.
Final expected output: (36,2048) or more general (k,2048).

In rpn_test_2.ipynb In [41] :
predictions = model([image_tensor]) 

I want to know have you done this.

I hope I am more clear now.

Thanks for your response.

**Comment by nithinraok** [comment]
I get your question now. Those features (36x2048) are pre-computed for VQA dataset and can be found here at https://imagecaption.blob.core.windows.net/imagecaption/trainval_36.zip. But if you would want to get new features for yourself on new set of images then refer to [this](https://github.com/peteanderson80/bottom-up-attention#demo) or any of Faster-rcnn repos.

**Comment by ak-kat** [comment]
Thanks.
Yes, I wanted to get new features for new set of images. Actually (https://github.com/peteanderson80/bottom-up-attention#demo) caffe implementation was creating so many issues, I found your repository (pytorch implementation) and thought to extract the same [using]it.

Thanks for your response.

**Comment by labheshpopli** [comment]
Hello,

I'm very new in the domain of VQA and trying to learn different methods that can be applied. Your detailed article on the topic and the code are very useful to get me started. Even though I have downloaded the code structure, installed Python 3.7, Anaconda 2019.07, I'm not sure where to start running the code and what steps to follow. Finally, how to demo with inputting images and questions, and getting an answer.

I would be grateful if you could help me with how to get started with this.

Thank You
