### ISSUE TITLE
Steps to run attention based VQA

### ISSUE THREAD

**Issue by labheshpopli** [nithinraok/VisualQuestion_VQA#2]
Hello,

I'm very new in the domain of VQA and trying to learn different methods that can be applied. Your detailed article on the topic and the code are very useful to get me started. Even though I have downloaded the code structure, installed Python 3.7, Anaconda 2019.07, I'm not sure where to start running the code and what steps to follow. Finally, how to demo with inputting images and questions, and getting an answer.

I would be grateful if you could help me with how to get started with this.

Thank You

**Comment by nithinraok** [comment]
Hello,

Thanks for your comments. This repo is not for demo purposes instead created as a part of our course project. But if you are keen on looking at it, for start you can see vqa_main.py in Visual_All directory. From there, you should be able to understand by digging into code.

**Comment by labheshpopli** [comment]
Thank you! I'll start looking at it.
